/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fashion.store.ui;

import java.awt.Frame;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import fashion.store.dao.BillDAO;
import fashion.store.dao.BillDetailDAO;
import fashion.store.dao.CustomerDAO;
import fashion.store.dao.impl.BillDAOImpl;
import fashion.store.dao.impl.BillDetailDAOImpl;
import fashion.store.dao.impl.CustomerDAOImpl;
import fashion.store.entity.Bill;
import fashion.store.entity.BillDetail;
import fashion.store.entity.Customer;
import fashion.store.ui.controller.BillController;
import fashion.store.util.XDate;
import fashion.store.util.XDialog;
import java.util.ArrayList;

/**
 *
 * @author PC
 */
public class BillJDialog extends javax.swing.JDialog implements BillController {

    /**
     * Creates new form BillJDialog
     */
    public BillJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtCheckin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCheckout = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBillDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboKhachHang = new javax.swing.JComboBox<>();
        txtTimKhachHang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiếu bán hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setText("Thời điểm thanh toán");

        txtId.setEditable(false);

        txtUsername.setEditable(false);

        txtStatus.setEditable(false);

        txtCheckin.setEditable(false);

        jLabel1.setText("Mã phiếu");

        txtCheckout.setEditable(false);

        jLabel2.setText("Khách hàng");

        tblBillDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Chọn", "Mã phiếu", "Sản phẩm", "Đơn giá", "Giảm giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBillDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBillDetails);

        jLabel3.setText("Thời điểm tạo");

        jLabel4.setText("Nhân viên ");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnRemove.setText("Xóa sản phẩm");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAdd.setText("Thêm sản phẩm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnCancel.setText("Hủy phiếu");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accept.png"))); // NOI18N
        btnCheckout.setText("Thanh toán");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Trạng thái");

        cboKhachHang.setMaximumRowCount(10);
        cboKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTimKhachHang.setText("jTextField1");
        txtTimKhachHang.setToolTipText("Nhập tên hoặc SĐT hoặc Mã khách hàng...");
        txtTimKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKhachHangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(cboKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBillDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillDetailsMouseClicked
        int row = tblBillDetails.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2 && row >= 0) {
            tblBillDetails.setRowSelectionInterval(row, row); // chọn dòng vừa click
            this.updateQuantity();
        }
    }//GEN-LAST:event_tblBillDetailsMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        this.removeProducts();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        this.showProductJDialog();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        this.checkout();
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.close();
    }//GEN-LAST:event_formWindowClosed

    private void txtTimKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKhachHangKeyReleased
        // TODO add your handling code here:
        String keyword = txtTimKhachHang.getText().trim().toLowerCase();
        cboKhachHang.removeAllItems();
        cboKhachHang.addItem("Vãng lai");
        for (Customer c : customers) {
            if (c.isEnabled()) {
                String id = c.getId().toLowerCase();
                String name = c.getName().toLowerCase();
                String phone = c.getPhone().toLowerCase();

                // Tìm theo mã, tên hoặc số điện thoại
                if (id.contains(keyword) || name.contains(keyword) || phone.contains(keyword)) {
                    cboKhachHang.addItem(c.getId() + " - " + c.getName());
                }
            }
        }
    }//GEN-LAST:event_txtTimKhachHangKeyReleased

    private Bill bill;
    private BillDAO billDao = new BillDAOImpl();
    private BillDetailDAO billDetailDao = new BillDetailDAOImpl();
    private CustomerDAO customerDao = new CustomerDAOImpl();
    private List<BillDetail> billDetails;
    private List<Customer> customers = new ArrayList<>();

    private void loadCustomers() {
        customers = customerDao.findAll();
        txtTimKhachHang.setText("");
        reloadComboBox(customers);
    }

    private void reloadComboBox(List<Customer> filteredList) {
        cboKhachHang.removeAllItems();
        cboKhachHang.addItem("Vãng lai");
        for (Customer c : filteredList) {
            if (c.isEnabled()) {
                cboKhachHang.addItem(c.getId() + " - " + c.getName());
            }
        }
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    @Override
    public void open() {
        this.loadCustomers();
        this.setForm(bill);
        this.fillBillDetails();
        this.setLocationRelativeTo(null);
    }

    // 4. close - hóa đơn không chi tiết thì chuyển trạng thái hủy
    @Override
    public void close() {
        if (billDetails.isEmpty() && bill.getStatus() == Bill.Status.Servicing) {
            bill.setStatus(Bill.Status.Canceled);
            billDao.update(bill);
        }
    }

    @Override
    public void showProductJDialog() {
        ProductJDialog dialog = new ProductJDialog((Frame) this.getOwner(), true);
        dialog.setBill(bill);
        dialog.setVisible(true);
        // Sau khi đóng dialog, luôn reload lại bảng
        this.fillBillDetails();
    }

    // 2. removeDrinks - Duyệt ngược, kiểm tra chỉ số, thêm thông báo
    @Override
    public void removeProducts() {
        boolean removed = false;
        for (int i = tblBillDetails.getRowCount() - 1; i >= 0; i--) {
            Boolean checked = (Boolean) tblBillDetails.getValueAt(i, 0);
            if (checked != null && checked && i < billDetails.size()) {
                billDetailDao.deleteById(billDetails.get(i).getId());
                removed = true;
            }
        }
        this.fillBillDetails();
        if (removed) {
            XDialog.success("Đã xóa sản phẩm.");
        } else {
            XDialog.warning("Vui lòng chọn sản phẩm cần xóa.");
        }
    }

    @Override
    public void updateQuantity() {
        if (bill.getStatus() == 0) {
            int row = tblBillDetails.getSelectedRow();
            if (row < 0) {
                return;
            }
            // Lấy ID từ bảng
            Object idObj = tblBillDetails.getValueAt(row, 1); // cột 1 là ID
            if (idObj == null) {
                return;
            }
            int billDetailId = Integer.parseInt(idObj.toString());
            // Tìm BillDetail theo ID
            BillDetail detail = billDetails.stream()
                    .filter(d -> d.getId() == billDetailId)
                    .findFirst().orElse(null);
            if (detail == null) {
                return;
            }

            String input = XDialog.prompt("Số lượng mới?");
            if (input != null && !input.isEmpty()) {
                try {
                    int qty = Integer.parseInt(input);
                    if (qty < 1) {
                        throw new NumberFormatException();
                    }
                    detail.setQuantity(qty);
                    billDetailDao.update(detail);
                    this.fillBillDetails();
                } catch (NumberFormatException ex) {
                    XDialog.warning("Số lượng phải là số nguyên dương!");
                }
            }
        }
    }

    // 3. checkout - tự tắt Form và báo thành công
    @Override
    public void checkout() {
        int selectedIndex = cboKhachHang.getSelectedIndex();
        double total = getTotalBillAmount();
        double originalTotal = total;
        double discountAmount = 0;
        String percentMsg = "";

        if (selectedIndex <= 0) {
            // Khách vãng lai
            bill.setCustomerId(null);
            if (originalTotal >= 500000) {
                discountAmount = originalTotal * 0.10;
                total = originalTotal - discountAmount;
                percentMsg = "Bạn được giảm giá 10%";
            } else {
                total = originalTotal;
                discountAmount = 0;
                percentMsg = "Bạn không được giảm giá";
            }
        } else {
            // Khách có tài khoản đã kích hoạt
            int activeIndex = -1;
            int count = 0;
            for (Customer c : customers) {
                if (c.isEnabled()) {
                    if (count == selectedIndex - 1) {
                        activeIndex = customers.indexOf(c);
                        break;
                    }
                    count++;
                }
            }
            bill.setCustomerId(customers.get(activeIndex).getId());

            Customer customer = customerDao.findById(bill.getCustomerId());
            if (customer != null && customer.isEnabled()) {
                // Luôn giảm 5%
                discountAmount = originalTotal * 0.05;
                total = originalTotal - discountAmount;
                percentMsg = "Bạn được giảm giá 5%";

                // Nếu tổng hóa đơn >= 500,000 giảm thêm 10%
                if (originalTotal >= 500000) {
                    double discount10 = originalTotal * 0.10;
                    total -= discount10;
                    discountAmount += discount10;
                    percentMsg = "Bạn được giảm giá 15%";
                }
            } else {
                // Nếu khách không hợp lệ, coi như vãng lai
                bill.setCustomerId(null);
                if (originalTotal >= 500000) {
                    discountAmount = originalTotal * 0.10;
                    total = originalTotal - discountAmount;
                    percentMsg = "Bạn được giảm giá 10%";
                } else {
                    total = originalTotal;
                    discountAmount = 0;
                    percentMsg = "Bạn không được giảm giá";
                }
            }
        }

        // Thông báo phần trăm và số tiền giảm giá nếu có
        if (discountAmount > 0) {
            XDialog.success(percentMsg + "\nTiết kiệm: " + String.format("%.2f", discountAmount));
        } else {
            XDialog.alert(percentMsg);
        }

        if (XDialog.confirm(String.format(
                "Tổng tiền hóa đơn: %.2f\nBạn muốn thanh toán phiếu bán hàng?", total))) {
            bill.setStatus(Bill.Status.Completed);
            bill.setCheckout(new Date());
            billDao.update(bill);
            this.setForm(bill);
            XDialog.success("Thanh toán thành công!\nTổng tiền: " + String.format("%.2f", total));
            this.dispose();
        }
    }

    @Override
    public void cancel() {
        if (billDetails.isEmpty()) {
            billDao.deleteById(bill.getId());
            this.dispose();
        } else if (XDialog.confirm("Bạn muốn hủy phiếu bán hàng?")) {
            bill.setStatus(Bill.Status.Canceled);
            billDao.update(bill);
            this.setForm(bill);
        }
    }

    private void setForm(Bill bill) {
        txtId.setText(String.valueOf(bill.getId()));
        if (bill.getCustomerId() == null) {
            cboKhachHang.setSelectedIndex(0); // vãng lai
        } else {
            // chọn đúng khách
            for (int i = 0; i < customers.size(); i++) {
                if (customers.get(i).getId().equals(bill.getCustomerId())) {
                    cboKhachHang.setSelectedIndex(i); // +1 vì vãng lai đứng đầu
                    break;
                }
            }
        }
        txtCheckin.setText(XDate.format(bill.getCheckin(), "HH:mm:ss dd-MM-yyyy"));
        txtUsername.setText(bill.getUsername());
        String[] statuses = {"Servicing", "Completed", "Canceled"};
        txtStatus.setText(statuses[bill.getStatus()]);
        if (bill.getCheckout() != null) {
            txtCheckout.setText(XDate.format(bill.getCheckout(), "HH:mm:ss dd-MM-yyyy"));
        }
        boolean editable = (bill.getStatus() == 0);
        btnAdd.setEnabled(editable);
        btnCancel.setEnabled(editable);
        btnCheckout.setEnabled(editable);
        btnRemove.setEnabled(editable);
    }

    // 1. fillBillDetails - Không tạo dòng trống
    private void fillBillDetails() {
        billDetails = billDetailDao.findByBillId(bill.getId());
        DefaultTableModel model = (DefaultTableModel) tblBillDetails.getModel();
        model.setRowCount(0);
        for (BillDetail d : billDetails) {
            Object[] row = {
                false, // Checkbox
                d.getId(), // Mã phiếu
                d.getProductName(), // Đồ uống
                d.getUnitPrice(), // Đơn giá
                String.format("%.0f%%", d.getDiscount() * 100), // Giảm giá
                d.getQuantity(), // Số lượng
                d.getTotalPrice() // Thành tiền
            };
            model.addRow(row);
        }
    }

    private double getTotalBillAmount() {
        double total = 0;
        for (BillDetail detail : billDetails) {
            total += detail.getTotalPrice();
        }
        return total;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillJDialog dialog = new BillJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBillDetails;
    private javax.swing.JTextField txtCheckin;
    private javax.swing.JTextField txtCheckout;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTimKhachHang;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
