/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashion.store.ui;

import java.io.File;
import fashion.store.util.XAuth;
import fashion.store.util.XIcon;
import fashion.store.ui.controller.FashionStoreController;
import fashion.store.util.XDate;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.SwingConstants;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author PC
 */
public final class FashinStoreJFrame extends javax.swing.JFrame implements FashionStoreController {

    /**
     * Creates new form PolyCafeJFrame
     */
    public FashinStoreJFrame() {
        initComponents();
        this.init(); // được gọi khi cửa sổ chưa được mở ra
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCenter = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnHoTro = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblFullname = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        pnlManager = new javax.swing.JPanel();
        btnCategoryManager = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        btnProductManager = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnXemGopYVaBaoCao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FashinStore trang chủ");

        pnlCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        pnlCenter.setForeground(new java.awt.Color(255, 153, 0));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnExit.setText("Kết thúc");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSales.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSales.setText("Bán hàng");
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesMouseExited(evt);
            }
        });
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHistory.setText("Lịch sử");
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistoryMouseExited(evt);
            }
        });
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePasswordMouseExited(evt);
            }
        });
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnHoTro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHoTro.setText("Hỗ trợ");
        btnHoTro.setPreferredSize(new java.awt.Dimension(133, 29));
        btnHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoTroActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setPreferredSize(new java.awt.Dimension(133, 29));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnHoTro, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(255, 0, 255));
        lblFullname.setText("Usertxt");

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/vr.jpg"))); // NOI18N

        pnlManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCategoryManager.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCategoryManager.setText("Loại sản phẩm");
        btnCategoryManager.setPreferredSize(new java.awt.Dimension(180, 50));
        btnCategoryManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategoryManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategoryManagerMouseExited(evt);
            }
        });
        btnCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCategoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 250, 79));

        btnBillManager.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBillManager.setText("Phiếu bán hàng");
        btnBillManager.setPreferredSize(new java.awt.Dimension(180, 50));
        btnBillManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillManagerMouseExited(evt);
            }
        });
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnBillManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 79));

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUserManager.setText("Người sử dụng");
        btnUserManager.setPreferredSize(new java.awt.Dimension(180, 50));
        btnUserManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserManagerMouseExited(evt);
            }
        });
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 250, 79));

        btnRevenueManager.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRevenueManager.setText("Doanh thu");
        btnRevenueManager.setPreferredSize(new java.awt.Dimension(180, 50));
        btnRevenueManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevenueManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevenueManagerMouseExited(evt);
            }
        });
        btnRevenueManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnRevenueManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 250, 79));

        btnProductManager.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnProductManager.setText("Sản phẩm");
        btnProductManager.setPreferredSize(new java.awt.Dimension(180, 50));
        btnProductManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductManagerMouseExited(evt);
            }
        });
        btnProductManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnProductManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 250, 79));

        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCustomer.setText("Quản lý khách hàng");
        btnCustomer.setPreferredSize(new java.awt.Dimension(180, 50));
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerMouseExited(evt);
            }
        });
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 250, 79));

        btnInventory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInventory.setText("Quản lý kho");
        btnInventory.setPreferredSize(new java.awt.Dimension(180, 50));
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventoryMouseExited(evt);
            }
        });
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        pnlManager.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 250, 79));

        btnXemGopYVaBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXemGopYVaBaoCao.setText("Xem góp ý & báo cáo");
        btnXemGopYVaBaoCao.setPreferredSize(new java.awt.Dimension(180, 50));
        btnXemGopYVaBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemGopYVaBaoCaoActionPerformed(evt);
            }
        });
        pnlManager.add(btnXemGopYVaBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 79));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/z6810740185137_0cbd4e0ccce8eeef13bd2384c29e97d7.jpg"))); // NOI18N
        pnlManager.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 111, 97));
        jLabel1.setText("VÉRON");

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblClock.setForeground(new java.awt.Color(0, 153, 255));
        lblClock.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoto)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblClock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        this.showBillJDialog(this);
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        this.showHistoryJDialog(this);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        this.showChangePasswordJDialog(this);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryManagerActionPerformed
        this.showCategoryManagerJDialog(this);
    }//GEN-LAST:event_btnCategoryManagerActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        this.showBillManagerJDialog(this);
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnRevenueManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueManagerActionPerformed
        this.showRevenueManagerJDialog(this);
    }//GEN-LAST:event_btnRevenueManagerActionPerformed

    private void btnProductManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductManagerActionPerformed
        this.showProductManagerJDialog(this);
    }//GEN-LAST:event_btnProductManagerActionPerformed

    private void btnSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSalesMouseEntered

    private void btnSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSalesMouseExited

    private void btnHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHistoryMouseEntered

    private void btnHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHistoryMouseExited

    private void btnChangePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnChangePasswordMouseEntered

    private void btnChangePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnChangePasswordMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExitMouseExited

    private void btnProductManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductManagerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnProductManagerMouseEntered

    private void btnProductManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductManagerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnProductManagerMouseExited

    private void btnBillManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillManagerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBillManagerMouseEntered

    private void btnBillManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillManagerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBillManagerMouseExited

    private void btnCategoryManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryManagerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCategoryManagerMouseEntered

    private void btnCategoryManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryManagerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCategoryManagerMouseExited

    private void btnUserManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserManagerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUserManagerMouseEntered

    private void btnUserManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserManagerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUserManagerMouseExited

    private void btnRevenueManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevenueManagerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRevenueManagerMouseEntered

    private void btnRevenueManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevenueManagerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRevenueManagerMouseExited

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        this.showCustomerManagerJDialog(this);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        this.showInventoryManagerJDialog(this);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCustomerMouseEntered

    private void btnCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCustomerMouseExited

    private void btnInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnInventoryMouseEntered

    private void btnInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnInventoryMouseExited

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        XAuth.user = null;
        this.showLoginJDialog(this);
        // Kiểm tra nếu user đăng nhập thành công
        if (XAuth.user != null) {
            this.init1();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoTroActionPerformed
        // TODO add your handling code here:   
        this.hoTro();
    }//GEN-LAST:event_btnHoTroActionPerformed

    private void btnXemGopYVaBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemGopYVaBaoCaoActionPerformed
        // TODO add your handling code here:
        try {
            File folder = new File("feedback");
            if (!folder.exists()) {
                JOptionPane.showMessageDialog(this, "Chưa có góp ý nào được ghi nhận!", "📭 Thư mục trống", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Desktop.getDesktop().open(folder);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thể mở thư mục góp ý: " + e.getMessage(), "❌ Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXemGopYVaBaoCaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FashinStoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FashinStoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FashinStoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FashinStoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FashinStoreJFrame().setVisible(true); // <- JFrame luôn được show ra
            }
        });
    }

    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("vr.jpg").getImage());
        this.setLocationRelativeTo(null);

        // Khởi tạo đồng hồ thời gian thực sử dụng XDate
        Timer timer = new Timer(1000, e -> {
            lblClock.setText(XDate.format(XDate.now(), "HH:mm:ss"));
        });
        timer.start();

        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);

        String photoName = XAuth.user.getPhoto();
        if (photoName == null || photoName.isBlank()) {
            photoName = "vr.jpg"; // hoặc ảnh mặc định
        }
        File file = new File("photos", photoName);
        if (file.exists()) {
            XIcon.setIcon(lblPhoto, file);
        } else {
            // Thử tìm trong resource icons
            java.net.URL url = getClass().getResource("/poly/cafe/icons/" + photoName);
            if (url == null) {
                // Thử tiếp trong resource img (tuỳ project)
                url = getClass().getResource("/img/" + photoName);
            }
            if (url != null) {
                lblPhoto.setIcon(new javax.swing.ImageIcon(url));
            } else {
                // fallback ảnh mặc định
                java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/vr.jpg");
                lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);
            }
        }
        lblFullname.setText(XAuth.user.getFullname());

        if (XAuth.user.isManager()) {
            // Quản lý: hiện đầy đủ các chức năng
            pnlManager.setVisible(true);
            btnRevenueManager.setVisible(true);
            btnUserManager.setVisible(true);
            btnCategoryManager.setVisible(true);
            btnProductManager.setVisible(true);
            btnBillManager.setVisible(true);
            btnInventory.setVisible(true);
            btnCustomer.setVisible(true);
            btnXemGopYVaBaoCao.setVisible(true);
        } else {
            // Nhân viên: Ẩn các chức năng quản lý không cần thiết
            btnRevenueManager.setVisible(false);
            btnUserManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnProductManager.setVisible(false);
            btnBillManager.setVisible(false);
            btnInventory.setVisible(false);
            btnCustomer.setVisible(false);
            btnXemGopYVaBaoCao.setVisible(false);
        }
    }

    public void init1() {
        this.setIconImage(XIcon.getIcon("vr.jpg").getImage());
        this.setLocationRelativeTo(null);

        // Đồng hồ thời gian thực
        Timer timer = new Timer(1000, e -> {
            lblClock.setText(XDate.format(XDate.now(), "HH:mm:ss"));
        });
        timer.start();

        // Kiểm tra đăng nhập
        if (XAuth.user == null) {
            lblFullname.setText("Khách");
            java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/vr.jpg");
            lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);

            pnlManager.setVisible(false); // Ẩn toàn bộ quản lý
            return; // dừng lại vì không có người dùng
        }

        String photoName = XAuth.user.getPhoto();
        if (photoName == null || photoName.isBlank()) {
            photoName = "vr.jpg";
        }

        File file = new File("photos", photoName);
        if (file.exists()) {
            XIcon.setIcon(lblPhoto, file);
        } else {
            java.net.URL url = getClass().getResource("/poly/cafe/icons/" + photoName);
            if (url == null) {
                url = getClass().getResource("/img/" + photoName);
            }
            if (url != null) {
                lblPhoto.setIcon(new javax.swing.ImageIcon(url));
            } else {
                java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/vr.jpg");
                lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);
            }
        }

        lblFullname.setText(XAuth.user.getFullname());

        if (XAuth.user.isManager()) {
            pnlManager.setVisible(true);
            btnRevenueManager.setVisible(true);
            btnUserManager.setVisible(true);
            btnCategoryManager.setVisible(true);
            btnProductManager.setVisible(true);
            btnBillManager.setVisible(true);
            btnInventory.setVisible(true);
            btnCustomer.setVisible(true);
            btnXemGopYVaBaoCao.setVisible(true);
        } else {
            btnRevenueManager.setVisible(false);
            btnUserManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnProductManager.setVisible(false);
            btnBillManager.setVisible(false);
            btnInventory.setVisible(false);
            btnCustomer.setVisible(false);
            btnXemGopYVaBaoCao.setVisible(false);
        }
    }

    private void hoTro() {
        hienThongTinHoTro();
        String loaiPhanHoi = chonLoaiPhanHoi();
        if (loaiPhanHoi != null) {
            xuLyPhanHoi(loaiPhanHoi);
        }
    }

// Hiển thị thông tin hỗ trợ cơ bản
    private void hienThongTinHoTro() {
        JOptionPane.showMessageDialog(this,
                "👗 FashionStore\n"
                + "Địa chỉ: 123 Lê Lợi, Quận 1, TP.HCM\n"
                + "Hotline: 1900 123 456\n"
                + "Email: contact@fashionstore.vn\n"
                + "Website: www.fashionstore.vn",
                "Thông tin hỗ trợ", JOptionPane.INFORMATION_MESSAGE);
    }

// Cho người dùng chọn loại phản hồi
    private String chonLoaiPhanHoi() {
        String[] options = {"Góp ý", "Báo lỗi", "Ý kiến khác", "Hủy"};
        int choice = JOptionPane.showOptionDialog(this,
                "Bạn muốn gửi thông tin gì?",
                "Phản hồi người dùng",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

        if (choice >= 0 && choice <= 2) {
            return options[choice];
        }
        return null;
    }

// Xử lý phản hồi dựa trên loại đã chọn
    private void xuLyPhanHoi(String loaiPhanHoi) {
        JTextArea textArea = new JTextArea(8, 40);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        ((AbstractDocument) textArea.getDocument()).setDocumentFilter(new DocumentSizeFilter(500)); // Giới hạn ký tự

        JLabel charCountLabel = new JLabel("Còn lại: 500 ký tự");
        charCountLabel.setHorizontalAlignment(SwingConstants.RIGHT);

        textArea.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                update();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                update();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                update();
            }

            private void update() {
                int length = textArea.getText().length();
                int remaining = 500 - length;
                charCountLabel.setText("Còn lại: " + Math.max(0, remaining) + " ký tự");
            }
        });

        JPanel panel = new JPanel(new BorderLayout(5, 5));
        panel.add(new JScrollPane(textArea), BorderLayout.CENTER);
        panel.add(charCountLabel, BorderLayout.SOUTH);

        int result = JOptionPane.showConfirmDialog(this, panel,
                "✍️ Nhập nội dung " + loaiPhanHoi.toLowerCase() + ":",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String feedback = textArea.getText().trim();

            if (feedback.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Bạn chưa nhập nội dung!",
                        "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String username = (XAuth.user != null) ? XAuth.user.getUsername() : "Khach";
            String timestamp = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            String fileTimestamp = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));

            File feedbackDir = new File("feedback");
            if (!feedbackDir.exists()) {
                feedbackDir.mkdirs();
            }

            String loaiFolder = loaiPhanHoi.toLowerCase().replace(" ", "_");
            File loaiDir = new File(feedbackDir, loaiFolder);
            if (!loaiDir.exists()) {
                loaiDir.mkdirs();
            }

            String filename = String.format("%s_%s_%s.txt", loaiFolder, username, fileTimestamp);
            File file = new File(loaiDir, filename);

            try (PrintWriter out = new PrintWriter(new FileWriter(file, true))) {
                out.println("Loại phản hồi: " + loaiPhanHoi);
                out.println("Thời gian: " + timestamp);
                out.println("Người dùng: " + username);
                out.println("Nội dung phản hồi:\n" + feedback);
                out.println("-----");

                // 👉 GHI THÊM VÀO FILE EXCEL
                try {
                    File excelFile = new File("feedback/phan_hoi.xlsx");
                    XSSFWorkbook workbook;
                    Sheet sheet;

                    if (excelFile.exists()) {
                        try (FileInputStream fis = new FileInputStream(excelFile)) {
                            workbook = new XSSFWorkbook(fis);
                            sheet = workbook.getSheetAt(0);
                        }
                    } else {
                        workbook = new XSSFWorkbook();
                        sheet = workbook.createSheet("Phản hồi");

                        Row header = sheet.createRow(0);
                        header.createCell(0).setCellValue("Loại");
                        header.createCell(1).setCellValue("Người dùng");
                        header.createCell(2).setCellValue("Thời gian");
                        header.createCell(3).setCellValue("Nội dung");
                    }

                    int lastRow = sheet.getLastRowNum() + 1;
                    Row row = sheet.createRow(lastRow);
                    row.createCell(0).setCellValue(loaiPhanHoi);
                    row.createCell(1).setCellValue(username);
                    row.createCell(2).setCellValue(timestamp);
                    row.createCell(3).setCellValue(feedback);

                    for (int i = 0; i < 4; i++) {
                        sheet.autoSizeColumn(i);
                    }

                    try (FileOutputStream fos = new FileOutputStream(excelFile)) {
                        workbook.write(fos);
                    }
                    workbook.close();

                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,
                            "⚠️ Ghi file Excel thất bại: " + ex.getMessage(),
                            "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                }

                // ✅ Thông báo thành công
                JOptionPane.showMessageDialog(this,
                        "✅ Đã ghi nhận " + loaiPhanHoi.toLowerCase() + ". Xin cảm ơn!");

                int openFile = JOptionPane.showConfirmDialog(this,
                        "Bạn có muốn xem lại nội dung vừa gửi?",
                        "Xem lại", JOptionPane.YES_NO_OPTION);

                if (openFile == JOptionPane.YES_OPTION && Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(file);
                }

            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this,
                        "❌ Lỗi ghi phản hồi: " + e.getMessage(),
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    class DocumentSizeFilter extends DocumentFilter {

        private int max;

        public DocumentSizeFilter(int max) {
            this.max = max;
        }

        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            if ((fb.getDocument().getLength() + string.length()) <= max) {
                super.insertString(fb, offset, string, attr);
            } else {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            if ((fb.getDocument().getLength() - length + text.length()) <= max) {
                super.replace(fb, offset, length, text, attrs);
            } else {
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnCategoryManager;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHoTro;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProductManager;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JButton btnXemGopYVaBaoCao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlManager;
    // End of variables declaration//GEN-END:variables
}
